/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutSessionIdIndexRouteImport } from './routes/checkout/$sessionId/index'
import { Route as CheckoutSessionIdApiPollRouteImport } from './routes/checkout/$sessionId/api/poll'
import { Route as CheckoutSessionIdApiMarkRedirectedRouteImport } from './routes/checkout/$sessionId/api/mark-redirected'
import { Route as ApiPublicV1WorkerClaimRouteImport } from './routes/api/public/v1/worker/claim'
import { Route as ApiPublicV1ProviderCallbackSessionIdRouteImport } from './routes/api/public/v1/provider-callback/$sessionId'
import { Route as ApiPublicV1CheckoutInitializeRouteImport } from './routes/api/public/v1/checkout/initialize'
import { Route as ApiPublicV1CheckoutSessionIdStatusRouteImport } from './routes/api/public/v1/checkout/$sessionId/status'
import { Route as ApiPublicV1WorkerJobsJobIdResultRouteImport } from './routes/api/public/v1/worker/jobs/$jobId/result'
import { Route as ApiPublicV1WorkerJobsJobIdHeartbeatRouteImport } from './routes/api/public/v1/worker/jobs/$jobId/heartbeat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSessionIdIndexRoute = CheckoutSessionIdIndexRouteImport.update({
  id: '/checkout/$sessionId/',
  path: '/checkout/$sessionId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSessionIdApiPollRoute =
  CheckoutSessionIdApiPollRouteImport.update({
    id: '/checkout/$sessionId/api/poll',
    path: '/checkout/$sessionId/api/poll',
    getParentRoute: () => rootRouteImport,
  } as any)
const CheckoutSessionIdApiMarkRedirectedRoute =
  CheckoutSessionIdApiMarkRedirectedRouteImport.update({
    id: '/checkout/$sessionId/api/mark-redirected',
    path: '/checkout/$sessionId/api/mark-redirected',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1WorkerClaimRoute = ApiPublicV1WorkerClaimRouteImport.update({
  id: '/api/public/v1/worker/claim',
  path: '/api/public/v1/worker/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ProviderCallbackSessionIdRoute =
  ApiPublicV1ProviderCallbackSessionIdRouteImport.update({
    id: '/api/public/v1/provider-callback/$sessionId',
    path: '/api/public/v1/provider-callback/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1CheckoutInitializeRoute =
  ApiPublicV1CheckoutInitializeRouteImport.update({
    id: '/api/public/v1/checkout/initialize',
    path: '/api/public/v1/checkout/initialize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1CheckoutSessionIdStatusRoute =
  ApiPublicV1CheckoutSessionIdStatusRouteImport.update({
    id: '/api/public/v1/checkout/$sessionId/status',
    path: '/api/public/v1/checkout/$sessionId/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1WorkerJobsJobIdResultRoute =
  ApiPublicV1WorkerJobsJobIdResultRouteImport.update({
    id: '/api/public/v1/worker/jobs/$jobId/result',
    path: '/api/public/v1/worker/jobs/$jobId/result',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1WorkerJobsJobIdHeartbeatRoute =
  ApiPublicV1WorkerJobsJobIdHeartbeatRouteImport.update({
    id: '/api/public/v1/worker/jobs/$jobId/heartbeat',
    path: '/api/public/v1/worker/jobs/$jobId/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout/$sessionId/': typeof CheckoutSessionIdIndexRoute
  '/checkout/$sessionId/api/mark-redirected': typeof CheckoutSessionIdApiMarkRedirectedRoute
  '/checkout/$sessionId/api/poll': typeof CheckoutSessionIdApiPollRoute
  '/api/public/v1/checkout/initialize': typeof ApiPublicV1CheckoutInitializeRoute
  '/api/public/v1/provider-callback/$sessionId': typeof ApiPublicV1ProviderCallbackSessionIdRoute
  '/api/public/v1/worker/claim': typeof ApiPublicV1WorkerClaimRoute
  '/api/public/v1/checkout/$sessionId/status': typeof ApiPublicV1CheckoutSessionIdStatusRoute
  '/api/public/v1/worker/jobs/$jobId/heartbeat': typeof ApiPublicV1WorkerJobsJobIdHeartbeatRoute
  '/api/public/v1/worker/jobs/$jobId/result': typeof ApiPublicV1WorkerJobsJobIdResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout/$sessionId': typeof CheckoutSessionIdIndexRoute
  '/checkout/$sessionId/api/mark-redirected': typeof CheckoutSessionIdApiMarkRedirectedRoute
  '/checkout/$sessionId/api/poll': typeof CheckoutSessionIdApiPollRoute
  '/api/public/v1/checkout/initialize': typeof ApiPublicV1CheckoutInitializeRoute
  '/api/public/v1/provider-callback/$sessionId': typeof ApiPublicV1ProviderCallbackSessionIdRoute
  '/api/public/v1/worker/claim': typeof ApiPublicV1WorkerClaimRoute
  '/api/public/v1/checkout/$sessionId/status': typeof ApiPublicV1CheckoutSessionIdStatusRoute
  '/api/public/v1/worker/jobs/$jobId/heartbeat': typeof ApiPublicV1WorkerJobsJobIdHeartbeatRoute
  '/api/public/v1/worker/jobs/$jobId/result': typeof ApiPublicV1WorkerJobsJobIdResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout/$sessionId/': typeof CheckoutSessionIdIndexRoute
  '/checkout/$sessionId/api/mark-redirected': typeof CheckoutSessionIdApiMarkRedirectedRoute
  '/checkout/$sessionId/api/poll': typeof CheckoutSessionIdApiPollRoute
  '/api/public/v1/checkout/initialize': typeof ApiPublicV1CheckoutInitializeRoute
  '/api/public/v1/provider-callback/$sessionId': typeof ApiPublicV1ProviderCallbackSessionIdRoute
  '/api/public/v1/worker/claim': typeof ApiPublicV1WorkerClaimRoute
  '/api/public/v1/checkout/$sessionId/status': typeof ApiPublicV1CheckoutSessionIdStatusRoute
  '/api/public/v1/worker/jobs/$jobId/heartbeat': typeof ApiPublicV1WorkerJobsJobIdHeartbeatRoute
  '/api/public/v1/worker/jobs/$jobId/result': typeof ApiPublicV1WorkerJobsJobIdResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout/$sessionId/'
    | '/checkout/$sessionId/api/mark-redirected'
    | '/checkout/$sessionId/api/poll'
    | '/api/public/v1/checkout/initialize'
    | '/api/public/v1/provider-callback/$sessionId'
    | '/api/public/v1/worker/claim'
    | '/api/public/v1/checkout/$sessionId/status'
    | '/api/public/v1/worker/jobs/$jobId/heartbeat'
    | '/api/public/v1/worker/jobs/$jobId/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout/$sessionId'
    | '/checkout/$sessionId/api/mark-redirected'
    | '/checkout/$sessionId/api/poll'
    | '/api/public/v1/checkout/initialize'
    | '/api/public/v1/provider-callback/$sessionId'
    | '/api/public/v1/worker/claim'
    | '/api/public/v1/checkout/$sessionId/status'
    | '/api/public/v1/worker/jobs/$jobId/heartbeat'
    | '/api/public/v1/worker/jobs/$jobId/result'
  id:
    | '__root__'
    | '/'
    | '/checkout/$sessionId/'
    | '/checkout/$sessionId/api/mark-redirected'
    | '/checkout/$sessionId/api/poll'
    | '/api/public/v1/checkout/initialize'
    | '/api/public/v1/provider-callback/$sessionId'
    | '/api/public/v1/worker/claim'
    | '/api/public/v1/checkout/$sessionId/status'
    | '/api/public/v1/worker/jobs/$jobId/heartbeat'
    | '/api/public/v1/worker/jobs/$jobId/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutSessionIdIndexRoute: typeof CheckoutSessionIdIndexRoute
  CheckoutSessionIdApiMarkRedirectedRoute: typeof CheckoutSessionIdApiMarkRedirectedRoute
  CheckoutSessionIdApiPollRoute: typeof CheckoutSessionIdApiPollRoute
  ApiPublicV1CheckoutInitializeRoute: typeof ApiPublicV1CheckoutInitializeRoute
  ApiPublicV1ProviderCallbackSessionIdRoute: typeof ApiPublicV1ProviderCallbackSessionIdRoute
  ApiPublicV1WorkerClaimRoute: typeof ApiPublicV1WorkerClaimRoute
  ApiPublicV1CheckoutSessionIdStatusRoute: typeof ApiPublicV1CheckoutSessionIdStatusRoute
  ApiPublicV1WorkerJobsJobIdHeartbeatRoute: typeof ApiPublicV1WorkerJobsJobIdHeartbeatRoute
  ApiPublicV1WorkerJobsJobIdResultRoute: typeof ApiPublicV1WorkerJobsJobIdResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$sessionId/': {
      id: '/checkout/$sessionId/'
      path: '/checkout/$sessionId'
      fullPath: '/checkout/$sessionId/'
      preLoaderRoute: typeof CheckoutSessionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$sessionId/api/poll': {
      id: '/checkout/$sessionId/api/poll'
      path: '/checkout/$sessionId/api/poll'
      fullPath: '/checkout/$sessionId/api/poll'
      preLoaderRoute: typeof CheckoutSessionIdApiPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$sessionId/api/mark-redirected': {
      id: '/checkout/$sessionId/api/mark-redirected'
      path: '/checkout/$sessionId/api/mark-redirected'
      fullPath: '/checkout/$sessionId/api/mark-redirected'
      preLoaderRoute: typeof CheckoutSessionIdApiMarkRedirectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/worker/claim': {
      id: '/api/public/v1/worker/claim'
      path: '/api/public/v1/worker/claim'
      fullPath: '/api/public/v1/worker/claim'
      preLoaderRoute: typeof ApiPublicV1WorkerClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/provider-callback/$sessionId': {
      id: '/api/public/v1/provider-callback/$sessionId'
      path: '/api/public/v1/provider-callback/$sessionId'
      fullPath: '/api/public/v1/provider-callback/$sessionId'
      preLoaderRoute: typeof ApiPublicV1ProviderCallbackSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/checkout/initialize': {
      id: '/api/public/v1/checkout/initialize'
      path: '/api/public/v1/checkout/initialize'
      fullPath: '/api/public/v1/checkout/initialize'
      preLoaderRoute: typeof ApiPublicV1CheckoutInitializeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/checkout/$sessionId/status': {
      id: '/api/public/v1/checkout/$sessionId/status'
      path: '/api/public/v1/checkout/$sessionId/status'
      fullPath: '/api/public/v1/checkout/$sessionId/status'
      preLoaderRoute: typeof ApiPublicV1CheckoutSessionIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/worker/jobs/$jobId/result': {
      id: '/api/public/v1/worker/jobs/$jobId/result'
      path: '/api/public/v1/worker/jobs/$jobId/result'
      fullPath: '/api/public/v1/worker/jobs/$jobId/result'
      preLoaderRoute: typeof ApiPublicV1WorkerJobsJobIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/worker/jobs/$jobId/heartbeat': {
      id: '/api/public/v1/worker/jobs/$jobId/heartbeat'
      path: '/api/public/v1/worker/jobs/$jobId/heartbeat'
      fullPath: '/api/public/v1/worker/jobs/$jobId/heartbeat'
      preLoaderRoute: typeof ApiPublicV1WorkerJobsJobIdHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutSessionIdIndexRoute: CheckoutSessionIdIndexRoute,
  CheckoutSessionIdApiMarkRedirectedRoute:
    CheckoutSessionIdApiMarkRedirectedRoute,
  CheckoutSessionIdApiPollRoute: CheckoutSessionIdApiPollRoute,
  ApiPublicV1CheckoutInitializeRoute: ApiPublicV1CheckoutInitializeRoute,
  ApiPublicV1ProviderCallbackSessionIdRoute:
    ApiPublicV1ProviderCallbackSessionIdRoute,
  ApiPublicV1WorkerClaimRoute: ApiPublicV1WorkerClaimRoute,
  ApiPublicV1CheckoutSessionIdStatusRoute:
    ApiPublicV1CheckoutSessionIdStatusRoute,
  ApiPublicV1WorkerJobsJobIdHeartbeatRoute:
    ApiPublicV1WorkerJobsJobIdHeartbeatRoute,
  ApiPublicV1WorkerJobsJobIdResultRoute: ApiPublicV1WorkerJobsJobIdResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
